# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'MouseToolbox' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MouseToolbox
   #自动布局库
  pod 'SnapKit'
  #数据库处理
  pod 'FMDB'
   #代码格式工具
  # pod 'SwiftLint'

end
